Add wrapper script to handle byobu grouped sessions automatically.

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -107,6 +107,98 @@ function sscr() {
   ssh -t $1 byobu -dR;
 }
 
+# Wrap a tmux byobu so that it uses grouped sessions to behave like screen
+function byobu() {
+  BYOBU=$(which byobu-tmux)
+  if [[ $# != 0 ]]; then
+    # Don't break existing commands
+    $BYOBU "$@"
+    return
+  fi
+  # Extract the session name, group number, and attached state from a session
+  # line that looks like:
+  # name: session_details [width x height] (optional group) (optional attached)
+  SESSION_REGEX='^([^:]*):[^[]*\[[^]]*\] ?(\([^)]*[0-9]\))? ?(\(attached\))?'
+  # Just check if the session is attached or not
+  ATTACHED_REGEX='\(attached\)$'
+  # Look for words of the form 'word0' and extract the word and the number
+  TRAILING_NUMBER_REGEX='^(.*[^0-9])?([0-9]+)$'
+  # If I read the command directly into the array, I get the xterm control code
+  # to change the window terminal.  This is a byobu bug, as calling tmux
+  # directly does not have the same problem.  We will work around it by calling
+  # tmux directly.
+  readarray -t SESSIONS <<< "$(tmux list-sessions 2>/dev/null)"
+  if [[ ${#SESSIONS[@]} -eq 1 ]]; then
+    if [[ -z "${SESSIONS[0]}" ]]; then
+      # No existing session, so start byobu with a specially named session
+      $BYOBU new -s group0
+    elif [[ ${SESSIONS[0]} =~ $ATTACHED_REGEX ]]; then
+      # Existing, attached session, so create a new session that groups to it
+      [[ ${SESSIONS[0]} =~ $SESSION_REGEX ]] || return -1
+      SESSION_NAME="${BASH_REMATCH[1]}"
+      [[ "${SESSION_NAME}" =~ $TRAILING_NUMBER_REGEX ]] \
+        && $BYOBU new-session -t "$SESSION_NAME" -s "${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))" \
+        || $BYOBU new-session -t "$SESSION_NAME" -s "${SESSION_NAME}0"
+    else
+      # Default behavior is to attach to an existing session, no matter the name
+      $BYOBU
+    fi
+    return
+  fi
+  # With multiple existing sessions, we have to get the name of the existing
+  # group (like the highlander, there can be only one), and either attach to
+  # the first free session, or create a new one if none are free.
+  GROUP_NAME=
+  FREE_GROUP_SESSION=
+  MAX_SESSION_NAME=
+  MAX_SESSION_NUM=
+  for SESSION in "${SESSIONS[@]}"; do
+    [[ ${SESSION} =~ $SESSION_REGEX ]] || return -1
+    if [[ -n "$GROUP_NAME" && -n "${BASH_REMATCH[2]}" && "$GROUP_NAME" != "${BASH_REMATCH[2]}" ]]; then
+      echo "ERROR: More than one group found"
+      $BYOBU list-sessions
+      return
+    fi
+    # Get the name of the group
+    if [[ -n "${BASH_REMATCH[2]}" ]]; then
+      GROUP_NAME="${BASH_REMATCH[2]}"
+      SESSION_NAME="${BASH_REMATCH[1]}"
+      if [[ "${SESSION_NAME}" =~ $TRAILING_NUMBER_REGEX ]]; then
+        if [[ ${BASH_REMATCH[2]} > $MAX_SESSION_NUM ]]; then
+          MAX_SESSION_NUM=${BASH_REMATCH[2]}
+          MAX_SESSION_NAME="${BASH_REMATCH[1]}"
+        fi
+      elif [[ -z "$MAX_SESSION_NAME" ]]; then
+        MAX_SESSION_NAME="$SESSION_NAME"
+        MAX_SESSION_NUM=0
+      fi
+      # else we already have a session at level 0, so MAX_SESSION isn't affected
+      if [[ ! $SESSION =~ $ATTACHED_REGEX ]]; then
+        # In the case of multiple free sessions, this just picks the one
+        # closest to the bottom of the list
+        FREE_GROUP_SESSION="$SESSION_NAME"
+      fi
+    fi
+    # else this is ungrouped session.  If that's the case, and all sessions are
+    # ungrouped, we can't choose which one to join, so we will happily fall
+    # through to the end.
+  done
+  if [[ -n "$FREE_GROUP_SESSION" ]]; then
+    $BYOBU attach -t "$FREE_GROUP_SESSION"
+    $BYOBU attach -t "$FREE_GROUP_SESSION"
+  elif [[ -n "$GROUP_NAME" ]]; then
+    # We are guaranteed to have a max session by the time we get here
+    $BYOBU new-session -t "$SESSION_NAME" -s "${MAX_SESSION_NAME}$((${MAX_SESSION_NUM} + 1))"
+  else
+    # We can only get here if we have no existing session group, and multiple
+    # ungrouped sessions, so we don't know which to join.  Let the user
+    # manually decide.
+    echo "ERROR: No group, but multiple sessions.  You must manually attach to a group"
+    return -1
+  fi
+}
+
+
 # Special command to highlight text
 function hl() { local R=$1; shift; egrep --color=always "|$R" $@; }
 
